version: '3'

services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: retry-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    ports:
      - "9000:9000"
    environment:
      PHP_IDE_CONFIG: "serverName=retry"
      XDEBUG_CONFIG: "client_host=host.docker.internal"
    networks:
      - retry-network

networks:
  retry-network:
    driver: bridge